[package]
name = "statspi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# atspi = { version = "0.17.0", default-features = false, features = ["tokio"] }
atspi = { path = "../atspi-arc-deref/atspi/atspi", default-features = false, features = ["tokio"] }
tokio = { version = "1.28.2", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
stream_stats = "0.1.1"
zbus = { version = "3.13.1", features = ["tokio"] }
