[package]
name = "statspi"
version = "0.1.0"
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# atspi = { version = "0.17.0", default-features = false, features = ["tokio"] }
atspi = { git = "https://github.com/odilia-app/atspi.git", branch="fix_prop_change_ev", default-features = false, features = ["tokio"] }
tokio = { version = "1.29.1", features = ["full", "time"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
zbus = { version = "3.13.1", features = ["tokio"] }
crossterm = "0.26.1"
tui = "0.19.0"
rand = "0.8.5"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
arch = "native"

[profile.dev]   
lto = false
opt-level = 0


