[package]
name = "statspi"
version = "0.1.0"
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# atspi = { version = "0.17.0", default-features = false, features = ["tokio"] }
atspi = { path = "../atspi-arc-deref/atspi/atspi", default-features = false, features = ["tokio"] }
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
zbus = { version = "3.13.1", features = ["tokio"] }
termion = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
arch = "native"

[profile.dev]   
lto = false
opt-level = 0


